"""Geração de MKVs sintéticos para testes (só mkvmerge; conteúdo inventado)."""

import os
import shutil
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path

import pytest

needs_mkvtoolnix = pytest.mark.skipif(
    shutil.which("mkvmerge") is None or shutil.which("mkvextract") is None,
    reason="MKVToolNix ausente",
)

ASS_HEAD = (
    "[Script Info]\n; Script generated by teste\nScriptType: v4.00+\nPlayResX: 1920\nPlayResY: 1080\n\n"
    "[V4+ Styles]\nFormat: Name, Fontname, Fontsize\nStyle: Default,Arial,48\nStyle: Sign-1,Arial,40\n\n"
    "[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"
)
SIGNS_EVENTS = [
    "Dialogue: 0,0:00:01.00,0:00:02.00,Sign-1,,0,0,0,,{\\pos(100,100)}Estação Central",
    "Dialogue: 0,0:00:01.04,0:00:02.00,Sign-1,,0,0,0,,{\\pos(101,100)}Estação Central",
]
DIALOGUE_EVENTS = [
    "Dialogue: 0,0:00:03.00,0:00:05.00,Default,,0,0,0,,Where are we going, friend?",
    "Dialogue: 0,0:00:05.50,0:00:07.00,Default,,0,0,0,,To the {\\i1}old{\\i0} station.",
]


def ass(events: list[str]) -> str:
    return ASS_HEAD + "".join(e + "\n" for e in events)


FULL_ASS = ass(SIGNS_EVENTS + DIALOGUE_EVENTS)
SIGNS_ASS = ass(SIGNS_EVENTS)
SRT = "1\n00:00:01,000 --> 00:00:02,000\nHello there, how are you?\n\n2\n00:00:03,000 --> 00:00:04,000\nI am fine.\n"


@dataclass
class Sub:
    content: str
    name: str
    lang: str = "en"
    ext: str = ".ass"
    default: bool = False
    forced: bool = False
    hearing_impaired: bool = False


def make_mkv(path: Path, subs: list[Sub], fonts: int = 1, age: float = 3600) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    work = path.parent / f".work-{path.stem}"
    work.mkdir(exist_ok=True)
    cmd = ["mkvmerge", "-q", "-o", str(path)]
    for i, sub in enumerate(subs):
        file = work / f"{i}{sub.ext}"
        file.write_text(sub.content, encoding="utf-8")
        cmd += [
            "--language", f"0:{sub.lang}",
            "--track-name", f"0:{sub.name}",
            "--default-track-flag", f"0:{'yes' if sub.default else 'no'}",
            "--forced-display-flag", f"0:{'yes' if sub.forced else 'no'}",
            "--hearing-impaired-flag", f"0:{'yes' if sub.hearing_impaired else 'no'}",
            str(file),
        ]  # fmt: skip
    for i in range(fonts):
        font = work / f"font{i}.ttf"
        font.write_bytes(b"\x00\x01\x00\x00fake-font")
        cmd += ["--attachment-mime-type", "font/ttf", "--attach-file", str(font)]
    subprocess.run(cmd, check=True, capture_output=True)
    shutil.rmtree(work)
    old = time.time() - age
    os.utime(path, (old, old))
    return path
