import pytest

from translaterany.subtitles.ass import AssError, ass_time_to_ms, has_marker, parse_ass, render_ass

HEADER = "[Script Info]\n; Script generated by Aegisub\nTitle: teste\nPlayResX: 1920\n\n"
STYLES = "[V4+ Styles]\nFormat: Name, Fontname\nStyle: Default,Arial\n\n"
EVENTS = (
    "[Events]\n"
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"
    "Comment: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,nota do typesetter\n"
    "Dialogue: 0,0:00:01.50,0:00:03.00,Default,Ana,0,0,0,,Olá, tudo bem, amigo?\n"
    "Dialogue: 1,0:01:02.25,0:01:04.00,Sign,,0,0,0,,{\\pos(10,20)}Placa\n"
)
EXTRA = "\n[Aegisub Extradata]\nData: 1,x,y\n"
SAMPLE = (HEADER + STYLES + EVENTS + EXTRA).encode("utf-8")


def test_roundtrip_is_byte_identical() -> None:
    assert render_ass(parse_ass(SAMPLE), {}) == SAMPLE


def test_events_and_commas_in_text() -> None:
    doc = parse_ass(SAMPLE)
    assert [e.kind for e in doc.events] == ["comment", "dialogue", "dialogue"]
    ev = doc.events[1]
    assert ev.text == "Olá, tudo bem, amigo?"
    assert ev.field("style") == "Default" and ev.field("Name") == "Ana"
    assert (ev.start_ms, ev.end_ms) == (1500, 3000)
    assert doc.events[2].start_ms == 62250


def test_crlf_and_bom_are_preserved() -> None:
    data = ("﻿" + (HEADER + STYLES + EVENTS).replace("\n", "\r\n")).encode("utf-8")
    doc = parse_ass(data)
    assert doc.bom and doc.newline == "\r\n"
    assert render_ass(doc, {}) == data
    changed = render_ass(doc, {1: "Oi"})
    assert b"Default,Ana,0,0,0,,Oi\r\n" in changed
    assert changed.startswith("﻿".encode())


def test_render_changes_only_the_text_field() -> None:
    doc = parse_ass(SAMPLE)
    out = render_ass(doc, {1: "Oi, tudo?"}).decode()
    assert "Dialogue: 0,0:00:01.50,0:00:03.00,Default,Ana,0,0,0,,Oi, tudo?\n" in out
    assert out.replace("Oi, tudo?", "Olá, tudo bem, amigo?") == SAMPLE.decode()


def test_custom_format_order() -> None:
    data = b"[Script Info]\n\n[Events]\nFormat: Start, End, Style, Text\nDialogue: 0:00:00.00,0:00:01.00,Default,a, b\n"
    doc = parse_ass(data)
    assert doc.events[0].text == "a, b" and doc.events[0].field("Style") == "Default"
    assert render_ass(doc, {}) == data


def test_marker_inserted_once_after_script_info() -> None:
    doc = parse_ass(SAMPLE)
    out = render_ass(doc, {}, marker=True)
    assert out.decode().startswith("[Script Info]\n; TranslaterAny\n")
    assert has_marker(out) and not has_marker(SAMPLE)
    again = render_ass(parse_ass(out), {}, marker=True)
    assert again.decode().count("; TranslaterAny") == 1


@pytest.mark.parametrize(
    ("data", "match"),
    [
        (b"[Script Info]\nTitle: x\n", r"\[Events\] ausente"),
        (b"[Events]\nDialogue: 0,0:00:00.00,0:00:01.00,D,,0,0,0,,x\n", "antes da linha Format"),
        (b"[Events]\nFormat: Layer, Text, Start\n", "Text precisa ser a última"),
        (b"[Events]\nFormat: Layer, Start, End, Text\nDialogue: 0,0:00:01.00\n", "campos a menos"),
        (b"[Events]\n", "Format ausente"),
        ("[Events]\nFormat: Text\nDialogue: é\n".encode("latin-1"), "não é UTF-8"),
    ],
)
def test_malformed(data: bytes, match: str) -> None:
    with pytest.raises(AssError, match=match):
        parse_ass(data)


def test_time_parsing() -> None:
    assert ass_time_to_ms("1:02:03.45") == 3723450
    with pytest.raises(AssError):
        ass_time_to_ms("abc")


def test_legacy_ssa_format_with_marked() -> None:
    data = (
        b"[Script Info]\nScriptType: v4.00\n\n[Events]\n"
        b"Format: Marked, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"
        b"Dialogue: Marked=0,0:00:01.00,0:00:02.00,Default,,0000,0000,0000,,Old, style\n"
    )
    doc = parse_ass(data)
    assert doc.events[0].text == "Old, style" and doc.events[0].start_ms == 1000
    assert render_ass(doc, {}) == data


def test_render_converts_literal_newlines_to_backslash_n() -> None:
    doc = parse_ass(SAMPLE)
    out = render_ass(doc, {1: "Linha 1\nLinha 2\r\nLinha 3"}).decode()
    assert "Dialogue: 0,0:00:01.50,0:00:03.00,Default,Ana,0,0,0,,Linha 1\\NLinha 2\\NLinha 3\n" in out

