"""Etapas embutidas. Importar este pacote registra todas elas no REGISTRY."""

from translaterany.stages import (  # noqa: F401
    adapt,
    classify,
    colloquial,
    consolidate_memory,
    extract,
    extract_terms,
    final_readthrough,
    inventory,
    merge_sentences,
    metadata,
    normalize,
    ocr,
    orthography,
    publish,
    qa_loop,
    quality_checks,
    redistribute_sentences,
    remux,
    review_meaning,
    scene_analysis,
    select_track,
    translate_dialogue,
    translate_signs,
    translate_songs,
    translation_memory,
    treatment_consistency,
    write,
)

# Pipeline usado quando não há [pipeline] no config (remux vem desabilitado; quality_checks mede o resultado).
DEFAULT_PIPELINE: tuple[str, ...] = (
    "inventory",
    "metadata",
    "select_track",
    "extract",
    "ocr",
    "normalize",
    "classify",
    "extract_terms",
    "consolidate_memory",
    "translation_memory",
    "merge_sentences",
    "scene_analysis",
    "translate_dialogue",
    "translate_signs",
    "translate_songs",
    "review_meaning",
    "colloquial",
    "treatment_consistency",
    "adapt",
    "orthography",
    "final_readthrough",
    "redistribute_sentences",
    "qa_loop",
    "write",
    "publish",
    "remux",
    "quality_checks",
)
